/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chipsandkings;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import org.thehecklers.dialogfx.DialogFX;



/**
 *
 * @author v
 */
public class MainGameboard extends javax.swing.JFrame {

    /**
     * Creates new form MainGameboard
     */
    public MainGameboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        A8 = new javax.swing.JLabel();
        B8 = new javax.swing.JLabel();
        C8 = new javax.swing.JLabel();
        D8 = new javax.swing.JLabel();
        E8 = new javax.swing.JLabel();
        F8 = new javax.swing.JLabel();
        G8 = new javax.swing.JLabel();
        H8 = new javax.swing.JLabel();
        A7 = new javax.swing.JLabel();
        B7 = new javax.swing.JLabel();
        C7 = new javax.swing.JLabel();
        D7 = new javax.swing.JLabel();
        E7 = new javax.swing.JLabel();
        F7 = new javax.swing.JLabel();
        G7 = new javax.swing.JLabel();
        H7 = new javax.swing.JLabel();
        A6 = new javax.swing.JLabel();
        B6 = new javax.swing.JLabel();
        C6 = new javax.swing.JLabel();
        D6 = new javax.swing.JLabel();
        E6 = new javax.swing.JLabel();
        F6 = new javax.swing.JLabel();
        G6 = new javax.swing.JLabel();
        H6 = new javax.swing.JLabel();
        A5 = new javax.swing.JLabel();
        B5 = new javax.swing.JLabel();
        C5 = new javax.swing.JLabel();
        D5 = new javax.swing.JLabel();
        E5 = new javax.swing.JLabel();
        F5 = new javax.swing.JLabel();
        G5 = new javax.swing.JLabel();
        H5 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        C4 = new javax.swing.JLabel();
        D4 = new javax.swing.JLabel();
        E4 = new javax.swing.JLabel();
        F4 = new javax.swing.JLabel();
        G4 = new javax.swing.JLabel();
        H4 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();
        C3 = new javax.swing.JLabel();
        D3 = new javax.swing.JLabel();
        E3 = new javax.swing.JLabel();
        F3 = new javax.swing.JLabel();
        G3 = new javax.swing.JLabel();
        H3 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        C2 = new javax.swing.JLabel();
        D2 = new javax.swing.JLabel();
        E2 = new javax.swing.JLabel();
        F2 = new javax.swing.JLabel();
        G2 = new javax.swing.JLabel();
        H2 = new javax.swing.JLabel();
        A1 = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        C1 = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        E1 = new javax.swing.JLabel();
        F1 = new javax.swing.JLabel();
        G1 = new javax.swing.JLabel();
        H1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));

        panel2.setPreferredSize(new java.awt.Dimension(480, 480));
        panel2.setLayout(new java.awt.GridLayout(8, 8, 1, 1));

        A8.setBackground(new java.awt.Color(255, 255, 255));
        A8.setToolTipText("");
        A8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        A8.setName("A8"); // NOI18N
        A8.setOpaque(true);
        A8.setPreferredSize(new java.awt.Dimension(60, 60));
        A8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(A8);
        A8.getAccessibleContext().setAccessibleName("A8");

        B8.setBackground(new java.awt.Color(0, 0, 0));
        B8.setToolTipText("");
        B8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        B8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B8.setName("jLabel1"); // NOI18N
        B8.setOpaque(true);
        B8.setPreferredSize(new java.awt.Dimension(60, 60));
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(B8);

        C8.setBackground(new java.awt.Color(255, 255, 255));
        C8.setToolTipText("");
        C8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        C8.setName("jLabel1"); // NOI18N
        C8.setOpaque(true);
        C8.setPreferredSize(new java.awt.Dimension(60, 60));
        C8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(C8);

        D8.setBackground(new java.awt.Color(0, 0, 0));
        D8.setToolTipText("");
        D8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        D8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        D8.setName("jLabel1"); // NOI18N
        D8.setOpaque(true);
        D8.setPreferredSize(new java.awt.Dimension(60, 60));
        D8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(D8);

        E8.setBackground(new java.awt.Color(255, 255, 255));
        E8.setToolTipText("");
        E8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        E8.setName("jLabel1"); // NOI18N
        E8.setOpaque(true);
        E8.setPreferredSize(new java.awt.Dimension(60, 60));
        E8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(E8);

        F8.setBackground(new java.awt.Color(0, 0, 0));
        F8.setToolTipText("");
        F8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        F8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        F8.setName("jLabel1"); // NOI18N
        F8.setOpaque(true);
        F8.setPreferredSize(new java.awt.Dimension(60, 60));
        F8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(F8);

        G8.setBackground(new java.awt.Color(255, 255, 255));
        G8.setToolTipText("");
        G8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        G8.setName("jLabel1"); // NOI18N
        G8.setOpaque(true);
        G8.setPreferredSize(new java.awt.Dimension(60, 60));
        G8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(G8);

        H8.setBackground(new java.awt.Color(0, 0, 0));
        H8.setToolTipText("");
        H8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        H8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H8.setName("jLabel1"); // NOI18N
        H8.setOpaque(true);
        H8.setPreferredSize(new java.awt.Dimension(60, 60));
        H8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(H8);

        A7.setBackground(new java.awt.Color(0, 0, 0));
        A7.setToolTipText("");
        A7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        A7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        A7.setName("jLabel1"); // NOI18N
        A7.setOpaque(true);
        A7.setPreferredSize(new java.awt.Dimension(60, 60));
        A7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(A7);

        B7.setBackground(new java.awt.Color(255, 255, 255));
        B7.setToolTipText("");
        B7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        B7.setName("jLabel1"); // NOI18N
        B7.setOpaque(true);
        B7.setPreferredSize(new java.awt.Dimension(60, 60));
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(B7);

        C7.setBackground(new java.awt.Color(0, 0, 0));
        C7.setToolTipText("");
        C7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        C7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        C7.setName("jLabel1"); // NOI18N
        C7.setOpaque(true);
        C7.setPreferredSize(new java.awt.Dimension(60, 60));
        C7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(C7);

        D7.setBackground(new java.awt.Color(255, 255, 255));
        D7.setToolTipText("");
        D7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        D7.setName("jLabel1"); // NOI18N
        D7.setOpaque(true);
        D7.setPreferredSize(new java.awt.Dimension(60, 60));
        D7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(D7);

        E7.setBackground(new java.awt.Color(0, 0, 0));
        E7.setToolTipText("");
        E7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        E7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        E7.setName("jLabel1"); // NOI18N
        E7.setOpaque(true);
        E7.setPreferredSize(new java.awt.Dimension(60, 60));
        E7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(E7);

        F7.setBackground(new java.awt.Color(255, 255, 255));
        F7.setToolTipText("");
        F7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        F7.setName("jLabel1"); // NOI18N
        F7.setOpaque(true);
        F7.setPreferredSize(new java.awt.Dimension(60, 60));
        F7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(F7);

        G7.setBackground(new java.awt.Color(0, 0, 0));
        G7.setToolTipText("");
        G7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        G7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        G7.setName("jLabel1"); // NOI18N
        G7.setOpaque(true);
        G7.setPreferredSize(new java.awt.Dimension(60, 60));
        G7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(G7);

        H7.setBackground(new java.awt.Color(255, 255, 255));
        H7.setToolTipText("");
        H7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        H7.setName("jLabel1"); // NOI18N
        H7.setOpaque(true);
        H7.setPreferredSize(new java.awt.Dimension(60, 60));
        H7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(H7);

        A6.setBackground(new java.awt.Color(255, 255, 255));
        A6.setToolTipText("");
        A6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        A6.setName("jLabel1"); // NOI18N
        A6.setOpaque(true);
        A6.setPreferredSize(new java.awt.Dimension(60, 60));
        A6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(A6);

        B6.setBackground(new java.awt.Color(0, 0, 0));
        B6.setToolTipText("");
        B6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        B6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B6.setName("jLabel1"); // NOI18N
        B6.setOpaque(true);
        B6.setPreferredSize(new java.awt.Dimension(60, 60));
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(B6);

        C6.setBackground(new java.awt.Color(255, 255, 255));
        C6.setToolTipText("");
        C6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        C6.setName("jLabel1"); // NOI18N
        C6.setOpaque(true);
        C6.setPreferredSize(new java.awt.Dimension(60, 60));
        C6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(C6);

        D6.setBackground(new java.awt.Color(0, 0, 0));
        D6.setToolTipText("");
        D6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        D6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        D6.setName("jLabel1"); // NOI18N
        D6.setOpaque(true);
        D6.setPreferredSize(new java.awt.Dimension(60, 60));
        D6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(D6);

        E6.setBackground(new java.awt.Color(255, 255, 255));
        E6.setToolTipText("");
        E6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        E6.setName("jLabel1"); // NOI18N
        E6.setOpaque(true);
        E6.setPreferredSize(new java.awt.Dimension(60, 60));
        E6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(E6);

        F6.setBackground(new java.awt.Color(0, 0, 0));
        F6.setToolTipText("");
        F6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        F6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        F6.setName("jLabel1"); // NOI18N
        F6.setOpaque(true);
        F6.setPreferredSize(new java.awt.Dimension(60, 60));
        F6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(F6);

        G6.setBackground(new java.awt.Color(255, 255, 255));
        G6.setToolTipText("");
        G6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        G6.setName("jLabel1"); // NOI18N
        G6.setOpaque(true);
        G6.setPreferredSize(new java.awt.Dimension(60, 60));
        G6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(G6);

        H6.setBackground(new java.awt.Color(0, 0, 0));
        H6.setToolTipText("");
        H6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        H6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H6.setName("jLabel1"); // NOI18N
        H6.setOpaque(true);
        H6.setPreferredSize(new java.awt.Dimension(60, 60));
        H6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(H6);

        A5.setBackground(new java.awt.Color(0, 0, 0));
        A5.setToolTipText("");
        A5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        A5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        A5.setName("jLabel1"); // NOI18N
        A5.setOpaque(true);
        A5.setPreferredSize(new java.awt.Dimension(60, 60));
        A5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(A5);

        B5.setBackground(new java.awt.Color(255, 255, 255));
        B5.setToolTipText("");
        B5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        B5.setName("jLabel1"); // NOI18N
        B5.setOpaque(true);
        B5.setPreferredSize(new java.awt.Dimension(60, 60));
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(B5);

        C5.setBackground(new java.awt.Color(0, 0, 0));
        C5.setToolTipText("");
        C5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        C5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        C5.setName("jLabel1"); // NOI18N
        C5.setOpaque(true);
        C5.setPreferredSize(new java.awt.Dimension(60, 60));
        C5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(C5);

        D5.setBackground(new java.awt.Color(255, 255, 255));
        D5.setToolTipText("");
        D5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        D5.setName("jLabel1"); // NOI18N
        D5.setOpaque(true);
        D5.setPreferredSize(new java.awt.Dimension(60, 60));
        D5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(D5);

        E5.setBackground(new java.awt.Color(0, 0, 0));
        E5.setToolTipText("");
        E5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        E5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        E5.setName("jLabel1"); // NOI18N
        E5.setOpaque(true);
        E5.setPreferredSize(new java.awt.Dimension(60, 60));
        E5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(E5);

        F5.setBackground(new java.awt.Color(255, 255, 255));
        F5.setToolTipText("");
        F5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        F5.setName("jLabel1"); // NOI18N
        F5.setOpaque(true);
        F5.setPreferredSize(new java.awt.Dimension(60, 60));
        F5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(F5);

        G5.setBackground(new java.awt.Color(0, 0, 0));
        G5.setToolTipText("");
        G5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        G5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        G5.setName("jLabel1"); // NOI18N
        G5.setOpaque(true);
        G5.setPreferredSize(new java.awt.Dimension(60, 60));
        G5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(G5);

        H5.setBackground(new java.awt.Color(255, 255, 255));
        H5.setToolTipText("");
        H5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        H5.setName("jLabel1"); // NOI18N
        H5.setOpaque(true);
        H5.setPreferredSize(new java.awt.Dimension(60, 60));
        H5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(H5);

        A4.setBackground(new java.awt.Color(255, 255, 255));
        A4.setToolTipText("");
        A4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        A4.setName("jLabel1"); // NOI18N
        A4.setOpaque(true);
        A4.setPreferredSize(new java.awt.Dimension(60, 60));
        A4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(A4);

        B4.setBackground(new java.awt.Color(0, 0, 0));
        B4.setToolTipText("");
        B4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        B4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B4.setName("jLabel1"); // NOI18N
        B4.setOpaque(true);
        B4.setPreferredSize(new java.awt.Dimension(60, 60));
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(B4);

        C4.setBackground(new java.awt.Color(255, 255, 255));
        C4.setToolTipText("");
        C4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        C4.setName("jLabel1"); // NOI18N
        C4.setOpaque(true);
        C4.setPreferredSize(new java.awt.Dimension(60, 60));
        C4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(C4);

        D4.setBackground(new java.awt.Color(0, 0, 0));
        D4.setToolTipText("");
        D4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        D4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        D4.setName("jLabel1"); // NOI18N
        D4.setOpaque(true);
        D4.setPreferredSize(new java.awt.Dimension(60, 60));
        D4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(D4);

        E4.setBackground(new java.awt.Color(255, 255, 255));
        E4.setToolTipText("");
        E4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        E4.setName("jLabel1"); // NOI18N
        E4.setOpaque(true);
        E4.setPreferredSize(new java.awt.Dimension(60, 60));
        E4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(E4);

        F4.setBackground(new java.awt.Color(0, 0, 0));
        F4.setToolTipText("");
        F4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        F4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        F4.setName("jLabel1"); // NOI18N
        F4.setOpaque(true);
        F4.setPreferredSize(new java.awt.Dimension(60, 60));
        F4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(F4);

        G4.setBackground(new java.awt.Color(255, 255, 255));
        G4.setToolTipText("");
        G4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        G4.setName("jLabel1"); // NOI18N
        G4.setOpaque(true);
        G4.setPreferredSize(new java.awt.Dimension(60, 60));
        G4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(G4);

        H4.setBackground(new java.awt.Color(0, 0, 0));
        H4.setToolTipText("");
        H4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        H4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H4.setName("jLabel1"); // NOI18N
        H4.setOpaque(true);
        H4.setPreferredSize(new java.awt.Dimension(60, 60));
        H4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(H4);

        A3.setBackground(new java.awt.Color(0, 0, 0));
        A3.setToolTipText("");
        A3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        A3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        A3.setName("jLabel1"); // NOI18N
        A3.setOpaque(true);
        A3.setPreferredSize(new java.awt.Dimension(60, 60));
        A3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(A3);

        B3.setBackground(new java.awt.Color(255, 255, 255));
        B3.setToolTipText("");
        B3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        B3.setName("jLabel1"); // NOI18N
        B3.setOpaque(true);
        B3.setPreferredSize(new java.awt.Dimension(60, 60));
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(B3);

        C3.setBackground(new java.awt.Color(0, 0, 0));
        C3.setToolTipText("");
        C3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        C3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        C3.setName("jLabel1"); // NOI18N
        C3.setOpaque(true);
        C3.setPreferredSize(new java.awt.Dimension(60, 60));
        C3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(C3);

        D3.setBackground(new java.awt.Color(255, 255, 255));
        D3.setToolTipText("");
        D3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        D3.setName("jLabel1"); // NOI18N
        D3.setOpaque(true);
        D3.setPreferredSize(new java.awt.Dimension(60, 60));
        D3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(D3);

        E3.setBackground(new java.awt.Color(0, 0, 0));
        E3.setToolTipText("");
        E3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        E3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        E3.setName("jLabel1"); // NOI18N
        E3.setOpaque(true);
        E3.setPreferredSize(new java.awt.Dimension(60, 60));
        E3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(E3);

        F3.setBackground(new java.awt.Color(255, 255, 255));
        F3.setToolTipText("");
        F3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        F3.setName("jLabel1"); // NOI18N
        F3.setOpaque(true);
        F3.setPreferredSize(new java.awt.Dimension(60, 60));
        F3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(F3);

        G3.setBackground(new java.awt.Color(0, 0, 0));
        G3.setToolTipText("");
        G3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        G3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        G3.setName("jLabel1"); // NOI18N
        G3.setOpaque(true);
        G3.setPreferredSize(new java.awt.Dimension(60, 60));
        G3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(G3);

        H3.setBackground(new java.awt.Color(255, 255, 255));
        H3.setToolTipText("");
        H3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        H3.setName("jLabel1"); // NOI18N
        H3.setOpaque(true);
        H3.setPreferredSize(new java.awt.Dimension(60, 60));
        H3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(H3);

        A2.setBackground(new java.awt.Color(255, 255, 255));
        A2.setToolTipText("");
        A2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        A2.setName("jLabel1"); // NOI18N
        A2.setOpaque(true);
        A2.setPreferredSize(new java.awt.Dimension(60, 60));
        A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(A2);

        B2.setBackground(new java.awt.Color(0, 0, 0));
        B2.setToolTipText("");
        B2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        B2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B2.setName("jLabel1"); // NOI18N
        B2.setOpaque(true);
        B2.setPreferredSize(new java.awt.Dimension(60, 60));
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(B2);

        C2.setBackground(new java.awt.Color(255, 255, 255));
        C2.setToolTipText("");
        C2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        C2.setName("jLabel1"); // NOI18N
        C2.setOpaque(true);
        C2.setPreferredSize(new java.awt.Dimension(60, 60));
        C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(C2);

        D2.setBackground(new java.awt.Color(0, 0, 0));
        D2.setToolTipText("");
        D2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        D2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        D2.setName("jLabel1"); // NOI18N
        D2.setOpaque(true);
        D2.setPreferredSize(new java.awt.Dimension(60, 60));
        D2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(D2);

        E2.setBackground(new java.awt.Color(255, 255, 255));
        E2.setToolTipText("");
        E2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        E2.setName("jLabel1"); // NOI18N
        E2.setOpaque(true);
        E2.setPreferredSize(new java.awt.Dimension(60, 60));
        E2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(E2);

        F2.setBackground(new java.awt.Color(0, 0, 0));
        F2.setToolTipText("");
        F2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        F2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        F2.setName("jLabel1"); // NOI18N
        F2.setOpaque(true);
        F2.setPreferredSize(new java.awt.Dimension(60, 60));
        F2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(F2);

        G2.setBackground(new java.awt.Color(255, 255, 255));
        G2.setToolTipText("");
        G2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        G2.setName("jLabel1"); // NOI18N
        G2.setOpaque(true);
        G2.setPreferredSize(new java.awt.Dimension(60, 60));
        G2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(G2);

        H2.setBackground(new java.awt.Color(0, 0, 0));
        H2.setToolTipText("");
        H2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        H2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H2.setName("jLabel1"); // NOI18N
        H2.setOpaque(true);
        H2.setPreferredSize(new java.awt.Dimension(60, 60));
        H2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(H2);

        A1.setBackground(new java.awt.Color(0, 0, 0));
        A1.setToolTipText("");
        A1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        A1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        A1.setName("jLabel1"); // NOI18N
        A1.setOpaque(true);
        A1.setPreferredSize(new java.awt.Dimension(60, 60));
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(A1);

        B1.setBackground(new java.awt.Color(255, 255, 255));
        B1.setToolTipText("");
        B1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        B1.setName("jLabel1"); // NOI18N
        B1.setOpaque(true);
        B1.setPreferredSize(new java.awt.Dimension(60, 60));
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(B1);

        C1.setBackground(new java.awt.Color(0, 0, 0));
        C1.setToolTipText("");
        C1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        C1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        C1.setName("jLabel1"); // NOI18N
        C1.setOpaque(true);
        C1.setPreferredSize(new java.awt.Dimension(60, 60));
        C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(C1);

        D1.setBackground(new java.awt.Color(255, 255, 255));
        D1.setToolTipText("");
        D1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        D1.setName("jLabel1"); // NOI18N
        D1.setOpaque(true);
        D1.setPreferredSize(new java.awt.Dimension(60, 60));
        D1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(D1);

        E1.setBackground(new java.awt.Color(0, 0, 0));
        E1.setToolTipText("");
        E1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        E1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        E1.setName("jLabel1"); // NOI18N
        E1.setOpaque(true);
        E1.setPreferredSize(new java.awt.Dimension(60, 60));
        E1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(E1);

        F1.setBackground(new java.awt.Color(255, 255, 255));
        F1.setToolTipText("");
        F1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        F1.setName("jLabel1"); // NOI18N
        F1.setOpaque(true);
        F1.setPreferredSize(new java.awt.Dimension(60, 60));
        F1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(F1);

        G1.setBackground(new java.awt.Color(0, 0, 0));
        G1.setToolTipText("");
        G1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        G1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        G1.setName("jLabel1"); // NOI18N
        G1.setOpaque(true);
        G1.setPreferredSize(new java.awt.Dimension(60, 60));
        G1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(G1);

        H1.setBackground(new java.awt.Color(255, 255, 255));
        H1.setToolTipText("");
        H1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        H1.setName("jLabel1"); // NOI18N
        H1.setOpaque(true);
        H1.setPreferredSize(new java.awt.Dimension(60, 60));
        H1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        panel2.add(H1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void F5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_F5MouseClicked
    
    public void setInitIcons(ImageIcon pw, ImageIcon pb, ImageIcon kw, ImageIcon kb){
        //<editor-fold defaultstate="collapsed">
        /*switch (ChooseFirstPlayerColor()) {
            case 1:

                break;
            default:

        }*/
        /*ChooseFirstPlayerColor();
        
        ImageIcon kb = new ImageIcon("_kb.png");
        Image image = kb.getImage(); // transform it 
        Image newimg = image.getScaledInstance(59, 59,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        kb = new ImageIcon(newimg);
        kb.getImage().flush();
        
        ImageIcon pb = new ImageIcon("_pb.png");
        Image image2 = pb.getImage(); // transform it 
        Image newimg2 = image2.getScaledInstance(59, 59,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        pb = new ImageIcon(newimg2);
        pb.getImage().flush();
        
        ImageIcon kw = new ImageIcon("_kw.png");
        Image image3 = kw.getImage(); // transform it 
        Image newimg3 = image3.getScaledInstance(59, 59,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        kw = new ImageIcon(newimg3);
        kw.getImage().flush();
        
        ImageIcon pw = new ImageIcon("_pw.png");
        Image image4 = pw.getImage(); // transform it 
        Image newimg4 = image4.getScaledInstance(59, 59,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        pw = new ImageIcon(newimg4);
        pw.getImage().flush();*/
        //</editor-fold>
        
        B3.setIcon(pw);
        B3.setOpaque(false);
        B2.setIcon(pw);
        B2.setOpaque(false);
        C3.setIcon(pw);
        C2.setIcon(pw);
        D3.setIcon(pw);
        D2.setIcon(pw);
        E3.setIcon(pw);
        E2.setIcon(pw);
        F3.setIcon(pw);
        F2.setIcon(pw);
        G3.setIcon(pw);
        G2.setIcon(pw);
        E1.setIcon(kw);
        
        B7.setIcon(pb);
        B6.setIcon(pb);
        C7.setIcon(pb);
        C6.setIcon(pb);
        D7.setIcon(pb);
        D6.setIcon(pb);
        E7.setIcon(pb);
        E6.setIcon(pb);
        F7.setIcon(pb);
        F6.setIcon(pb);
        G7.setIcon(pb);
        G6.setIcon(pb);
        D1.setIcon(kb);
    }
    
    /*public static int ChooseFirstPlayerColor(){
        int a = (int)Math.round(Math.random());
        DialogFX dialog = new DialogFX();
        dialog.setTitleText("Player1 color is: ");
        String msg = "";
        switch(a){
            case 1: 
                msg = "White";
                break;
            default:
                msg = "White";
        }
        dialog.setMessage(msg);
        dialog.showDialog();
        return a; 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGameboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGameboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGameboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGameboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainGameboard().setVisible(true);
        });
        
        //PrepareSets();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel A5;
    private javax.swing.JLabel A6;
    private javax.swing.JLabel A7;
    private javax.swing.JLabel A8;
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel B3;
    private javax.swing.JLabel B4;
    private javax.swing.JLabel B5;
    private javax.swing.JLabel B6;
    private javax.swing.JLabel B7;
    private javax.swing.JLabel B8;
    private javax.swing.JLabel C1;
    private javax.swing.JLabel C2;
    private javax.swing.JLabel C3;
    private javax.swing.JLabel C4;
    private javax.swing.JLabel C5;
    private javax.swing.JLabel C6;
    private javax.swing.JLabel C7;
    private javax.swing.JLabel C8;
    private javax.swing.JLabel D1;
    private javax.swing.JLabel D2;
    private javax.swing.JLabel D3;
    private javax.swing.JLabel D4;
    private javax.swing.JLabel D5;
    private javax.swing.JLabel D6;
    private javax.swing.JLabel D7;
    private javax.swing.JLabel D8;
    private javax.swing.JLabel E1;
    private javax.swing.JLabel E2;
    private javax.swing.JLabel E3;
    private javax.swing.JLabel E4;
    private javax.swing.JLabel E5;
    private javax.swing.JLabel E6;
    private javax.swing.JLabel E7;
    private javax.swing.JLabel E8;
    private javax.swing.JLabel F1;
    private javax.swing.JLabel F2;
    private javax.swing.JLabel F3;
    private javax.swing.JLabel F4;
    private javax.swing.JLabel F5;
    private javax.swing.JLabel F6;
    private javax.swing.JLabel F7;
    private javax.swing.JLabel F8;
    private javax.swing.JLabel G1;
    private javax.swing.JLabel G2;
    private javax.swing.JLabel G3;
    private javax.swing.JLabel G4;
    private javax.swing.JLabel G5;
    private javax.swing.JLabel G6;
    private javax.swing.JLabel G7;
    private javax.swing.JLabel G8;
    private javax.swing.JLabel H1;
    private javax.swing.JLabel H2;
    private javax.swing.JLabel H3;
    private javax.swing.JLabel H4;
    private javax.swing.JLabel H5;
    private javax.swing.JLabel H6;
    private javax.swing.JLabel H7;
    private javax.swing.JLabel H8;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
